name: repositories
description: repositories
publish_to: 'none'
version: 1.0.0+1

environment:
  # sdk: '>=3.1.0-9.0.dev <4.0.0'
  sdk: ">=2.19.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cache:
    path: ../cache
  models:
    path: ../models
  
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
